### PR TITLE
Fixed links in Technical-Components.md and many more

### PR DESCRIPTION
**Pull request by Phoenix-Starlight**
Fixed links (Slimefun4-Wiki to Slimefun4/wiki/).

### CODE REVIEW

**Review by LinoxGH — APPROVED** [review]

**Review by poma123 — APPROVED** [review]

**Comment by WalshyDev** [comment]
While this is correct, you may as well also just generally update these. They're still linking to TheBusyBiscuit whereas it's now under Slimefun.

Should be https://github.com/Slimefun/Slimefun4/wiki/...

**Comment by Phoenix-Starlight** [comment]
Ok. i will edit the updated page.

**Comment by Phoenix-Starlight** [comment]
Ok, just did a mass search and replace to make the links that pointed to BusyBiscuit's wiki to Slimefun organization's wiki

**Comment by LinoxGH** [comment]
Uh oh this will take a loooong time to review. Well I gurss GL Walshy and Biscuit.

**Review by WalshyDev — APPROVED** [review]
Haha I only meant the file you were modifying. It's alright though, this LGTM

**Comment by Phoenix-Starlight** [comment]
Yayyy

**Pull request merged**
